[package]
name = "mathlab-yew"
version = "0.5.0"
edition = "2021"

[dependencies]
yew = { version="0.21.0", features = ["csr"]}
yew-plotly = "0.3.0"
wasm-bindgen = "0.2.93"
chrono = "0.4.38"
mathlab = "0.9.2"
